# Generated by Django 4.0.4 on 2022-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('ninterface', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('ipv4mode', models.CharField(max_length=50)),
                ('ipv4IpAddress', models.CharField(blank=True, max_length=50)),
                ('ipv4BitMask', models.CharField(blank=True, max_length=50)),
                ('ipv4Gateway', models.CharField(blank=True, max_length=50)),
                ('ipv4Dns', models.CharField(blank=True, max_length=100)),
                ('ipv6mode', models.CharField(max_length=50)),
                ('ipv6IpAddress', models.CharField(blank=True, max_length=50)),
                ('ipv6Prefix', models.CharField(blank=True, max_length=50)),
                ('ipv6Gateway', models.CharField(blank=True, max_length=50)),
                ('ipv6Dns', models.CharField(blank=True, max_length=100)),
                ('automaticConection', models.BooleanField(default=True)),
                ('primaryConection', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
